=== nasa/cumulus/tasks/cnm-to-cma/resources/cumulus_sns_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "file": {
      "type": "object",
      "properties": {
        "type": {
          "description": "The type of file. science files (netcdf, HDF, binary) should use the 'data' type. More can be added if need and consensus demand.",
          "type": "string",
          "enum": [
            "data",
            "browse",
            "metadata",
            "ancillary",
            "linkage"
          ]
        },
        "subtype": {
          "description": "An optional, specific implmentation of the file::type. e.g. NetCDF for a file of type 'data'",
          "type": "string"
        },
        "uri": {
          "description": "the URI of the file (s3://...)",
          "type": "string"
        },
        "name": {
          "description": "The human readable filename that this file represents. ",
          "type": "string"
        },
        "checksumType": {
          "description  ": "Type of the checksum (e.g. md5). Optional. If no checksumType is defined for a file, it is assumed to be md5",
          "type": "string",
          "enum": [
            "SHA512",
            "SHA256",
            "SHA2",
            "SHA1",
            "md5"
          ]
        },
        "checksum": {
          "description": "Checksum of the file.",
          "type": "string"
        },
        "size": {
          "description": "Size, in bytes, of the file.",
          "type": "number"
        }
      },
      "required": [
        "type",
        "uri",
        "size",
        "name"
      ]
    },
    "filegroup": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "string id of the filegroup by which all files are associated."
        },
        "files": {
          "description": "array of files that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        }
      },
      "required": [
        "id",
        "files"
      ]
    },
    "collection": {
      "description": "The collection short name and version.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "collection short name."
        },
        "version": {
          "type": "string",
          "description": "collection version."
        }
      },
      "required": [
        "name",
        "version"
      ]
    }
  },
  "title": "Cloud Notification Message (cnm) 1.2 ",
  "description": "A message format to trigger or respond to processing. Version 1.2",
  "type": "object",
  "properties": {
    "version": {
      "description": "The CNM Version used. e.g. '1.3'",
      "type": "string",
      "enum": [
        "1.0",
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.4.1",
        "1.5",
        "1.5.1",
        "1.6.0",
        "1.6.1-alpha.0"
      ]
    },
    "receivedTime": {
      "description": "Time message was received by the ingest system",
      "type": "string",
      "format": "date-time"
    },
    "processCompleteTime": {
      "description": "The time processing completed by the receiving entity.",
      "type": "string",
      "format": "date-time"
    },
    "submissionTime": {
      "description": "The time the message was created (and presumably sent) to the publication mechanism.",
      "type": "string",
      "format": "date-time"
    },
    "identifier": {
      "description": "Unique identifier for the message as a whole. It is the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.",
      "type": "string"
    },
    "collection": {
      "description": "The collection to which these granules will belong.",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/collection"
        }
      ]
    },
    "provider": {
      "description": "the name of the provider (e.g. SIP, SDS, etc. ) producing these files.",
      "type": "string"
    },
    "trace": {
      "description": "Information on the message or who is sending it.",
      "type": "string"
    },
    "response": {
      "description": "The response message type sent. Can be a success message or error message. Akin to both the PAN and PDRD",
      "type": "object",
      "properties": {
        "status": {
          "description": "Successful or error.",
          "type": "string",
          "enum": [
            "SUCCESS",
            "FAILURE"
          ]
        },
        "ingestionMetadata": {
          "description": "Object defining ingestion metadata, like CMR Concept IDs, URLS, etc",
          "type": "object",
          "properties": {
            "catalogId": {
              "description": "Identifier for catalog",
              "type": "string"
            },
            "catalogUrl": {
              "description": "URL of catalog entry",
              "type": "string"
            }
          }
        },
        "errorCode": {
          "description": "Error message. Success messages can be ignored.",
          "type": "string",
          "enum": [
            "VALIDATION_ERROR",
            "PROCESSING_ERROR",
            "TRANSFER_ERROR"
          ]
        },
        "errorMessage": {
          "description": "The message error for the failure that occured.",
          "type": "string"
        }
      },
      "required": [
        "status"
      ]
    },
    "product": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Identifier/name of the product",
          "type": "string"
        },
        "dataVersion": {
          "description": "Version of this product",
          "type": "string"
        },
        "dataProcessingType": {
          "description": "The type of data processing stream that generated the product",
          "type": "string",
          "enum": [
            "forward",
            "reprocessing"
          ]
        },
        "files": {
          "description": "array of files that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "filegroups": {
          "description": "array of filegroups that make up this product",
          "type": "array",
          "items": {
            "$ref": "#/definitions/filegroup"
          }
        }
      },
      "oneOf": [
        {
          "required": [
            "name",
            "files"
          ]
        },
        {
          "required": [
            "name",
            "filegroups"
          ]
        }
      ]
    }
  },
  "oneOf": [
    {
      "required": [
        "version",
        "submissionTime",
        "collection",
        "identifier",
        "product"
      ],
      "not": {
        "required": [
          "response"
        ]
      }
    },
    {
      "required": [
        "version",
        "receivedTime",
        "processCompleteTime",
        "submissionTime",
        "identifier",
        "collection",
        "response"
      ]
    }
  ]
}

=== nasa/cumulus/example/spec/parallel/cnmWorkflow/data/records/L2_HR_PIXC_product_0001-of-4154_dupe.json
{
  "version": "1.5",
  "provider": "PODAAC_SWOT",
  "collection": "L2_HR_PIXC",
  "submissionTime": "2017-10-01T05:45:29.000000Z",
  "identifier": "<<REPLACED with random string>>",
  "product": {
    "name": "L2_HR_PIXC_product_0001-of-4154",
    "dataVersion": "099",
    "files": [
      {
        "type": "data",
        "uri": "s3://<replace-bucket>/cumulus-test-data/pdrs/L2_HR_PIXC_product_0001-of-4154.h5",
        "name": "L2_HR_PIXC_product_0001-of-4154.h5",
        "checksumType": "md5",
        "checksum": "873baafd6d3a411561702e29576e4ac4",
        "size": 51
      }
    ]
  }
}

=== nasa/cumulus/tasks/cnm-to-cma/tests/resources/cumulus_sns_v1.0_notification.json
{
  "version":"1.0",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "product":
    {
      "name": "sampleGranuleName001",
      "dataVersion": "001",
      "files": [
        {
          "type": "data",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.nc",
          "name":"production_file.nc",
          "checksumType": "md5",
          "checksum": "4241jafkjaj14jasjf",
          "size": 123456
        },
        {
          "type": "browse",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file.png",
          "name":"production_file.png",
          "checksumType": "md5",
          "checksum": "addjd872342bfbf",
          "size": 12345
        }
      ]
    }
}

=== nasa/cumulus/tasks/get-cnm/tests/integration_tests/get-cnm/cnm.json
{
    "version": "1.3",
    "submissionTime": "2026-02-25T02:32:12",
    "identifier": "78b52d92-ff70-4633-94b1-94e10bf03d11",
    "collection": "[collection name]",
    "provider": "[provider name]",
    "product": {
      "name": "ATL08_20260222023208_00000000_006_02.h5_9UBgbmQK",
      "dataVersion": "[collection version]",
      "files": [
        {
          "name": "[file name]",
          "type": "data",
          "uri": "[uri]",
          "size": 0
        }
      ]
    }
  }

=== nasa/cumulus/tasks/cnm-to-cma/tests/resources/cumulus_sns_v1.1_filegroups_multiple.json
{
  "version":"1.1",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "product":
    {
      "name": "sampleGranuleName001",
      "dataVersion": "001",
      "filegroups" : [{
        "id" : "filgroup1",
        "files": [
          {
            "type": "data",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file1.nc",
            "name":"production_file1.nc",
            "checksumType": "md5",
            "checksum": "4241jafkjaj14jasjf",
            "size": 123456
          },
          {
            "type": "browse",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file1.png",
            "name":"production_file1.png",
            "checksumType": "md5",
            "checksum": "addjd872342bfbf",
            "size": 12345
          }
        ]
      },
      {
        "id" : "filgroup2",
        "files": [
          {
            "type": "data",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file2.nc",
            "name":"production_file2.nc",
            "checksumType": "md5",
            "checksum": "54241jafkjaj14jasjf",
            "size": 223456
          },
          {
            "type": "browse",
            "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/production_file2.png",
            "name":"production_file2.png",
            "checksumType": "md5",
            "checksum": "aaddjd872342bfbf",
            "size": 22345
          }
        ]
      }]
   }
}

=== nasa/cumulus/tasks/cnm-to-cma/tests/resources/cumulus_sns_v1.0_JA1_GPN_E.json
{
  "version": "1.4",
  "provider": "NASA/JPL/PO.DAAC",
  "collection": "JASON-1_L2_OST_GPN_E",
  "submissionTime": "2020-11-20T05:56:37.396264Z",
  "identifier": "f6595030-0342-4750-982d-42db2f68deca",
  "product": {
    "name": "JA1_GPN_2PeP001_002_20020115_060706_20020115_070316.nc",
    "files": [
      {
        "uri": "s3://podaac-ops-cumulus-staging/f6595030-0342-4750-982d-42db2f68deca/store/jason1/open/L2/gdr_netcdf_e/c001/JA1_GPN_2PeP001_002_20020115_060706_20020115_070316.nc",
        "checksum": "fcf863f73fb3ab1a1de47db96440e8f8",
        "size": 3683868,
        "type": "data",
        "name": "JA1_GPN_2PeP001_002_20020115_060706_20020115_070316.nc",
        "checksumType": "md5"
      },
      {
        "uri": "s3://podaac-ops-cumulus-staging/f6595030-0342-4750-982d-42db2f68deca/store/jason1/open/L2/gdr_netcdf_e/c001/JA1_GPN_2PeP001_002_20020115_060706_20020115_070316.nc.md5",
        "checksum": "f648734a7d36bbf5df1322d8131a96f4",
        "size": 88,
        "type": "metadata",
        "name": "JA1_GPN_2PeP001_002_20020115_060706_20020115_070316.nc.md5",
        "checksumType": "md5"
      }
    ],
    "dataVersion": "E"
  }
}

=== nasa/cumulus/tasks/cnm-to-cma/tests/resources/cumulus_sns_v1.0_notification_for_granuleRegex.json
{
  "version":"1.0",
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "submissionTime":"2017-09-30T03:42:29.791198Z",
  "identifier": "1234-abcd-efg0-9876",
  "product":
    {
      "name": "/myPath/mypath1/mypath2/OPS_granule_L2_GLA_H_20220101T000000_20220101T001500_0001.nc",
      "dataVersion": "001",
      "files": [
        {
          "type": "data",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/OPS_granule_L2_GLA_H_20220101T000000_20220101T001500_0001.nc",
          "name":"OPS_granule_L2_GLA_H_20220101T000000_20220101T001500_0001.nc",
          "checksumType": "md5",
          "checksum": "4241jafkjaj14jasjf",
          "size": 823456
        },
        {
          "type": "browse",
          "uri": "s3://sampleIngestBucket/prod_20170926T11:30:36/OPS_granule_L2_GLA_H_20220101T000000_20220101T001500_0001.png",
          "name":"OPS_granule_L2_GLA_H_20220101T000000_20220101T001500_0001.png",
          "checksumType": "md5",
          "checksum": "addjd872342bfbf",
          "size": 73456
        }
      ]
    }
}

=== nasa/cumulus/example/spec/parallel/cnmWorkflow/data/records/ascat_20121029_010301_metopb_00588_eps_o_coa_2101_ovw.l2.json
{
  "version": "1.4",
  "provider": "NASA/JPL/PO.DAAC",
  "collection": "ASCATB-L2-Coastal/op",
  "submissionTime": "2022-08-10T17:49:30.477188Z",
  "identifier": "<<REPLACED with random string>>",
  "product": {
    "name": "ascat_20121029_010301_metopb_00588_eps_o_coa_2101_ovw.l2",
    "files": [
      {
        "uri": "s3://<replace-bucket>/cumulus-test-data/pdrs/ascat_20121029_010301_metopb_00588_eps_o_coa_2101_ovw.l2.nc",
        "checksum": "f8a8fd0c4464252abb2e4815f643a185",
        "size": 3183706,
        "type": "data",
        "name": "ascat_20121029_010301_metopb_00588_eps_o_coa_2101_ovw.l2.nc",
        "checksumType": "md5"
      }
    ],
    "dataVersion": "Operational/Near-Real-Time"
  }
}
